name: Daily Stats Report

on:
  schedule:
    - cron: "0 0 * * *" # Runs at 00:00 UTC every day
  workflow_dispatch: # Allows manual trigger

jobs:
  send-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install node-fetch

      - name: Create stats script
        run: |
          cat > stats.js << 'EOL'
          const fetch = require('node-fetch');
          const fs = require('fs');

          async function getStats() {
              try {
                  const response = await fetch('https://obscureozy.goatcounter.com/api/v0/stats/export/json');
                  const data = await response.json();
                  
                  // Get today's stats
                  const today = new Date().toISOString().split('T')[0];
                  const todayStats = data.find(day => day.day === today);
                  
                  if (todayStats) {
                      const report = `# Website Analytics Report - ${today}\n\n` +
                                    `## Daily Statistics\n\n` +
                                    `| Metric | Count |\n` +
                                    `|--------|-------|\n` +
                                    `| Total Visitors | ${todayStats.total} |\n` +
                                    `| Unique Visitors | ${todayStats.unique} |\n` +
                                    `| Pageviews | ${todayStats.pageviews} |\n\n` +
                                    `## Weekly Summary\n\n` +
                                    `| Date | Total Visitors | Unique Visitors | Pageviews |\n` +
                                    `|------|---------------|----------------|----------|\n`;
                      
                      // Get last 7 days stats
                      const last7Days = data.slice(-7);
                      last7Days.forEach(day => {
                          report += `| ${day.day} | ${day.total} | ${day.unique} | ${day.pageviews} |\n`;
                      });
                      
                      // Write to a file that will be committed
                      fs.writeFileSync('analytics/daily-stats.md', report);
                      console.log('Stats saved successfully');
                  } else {
                      console.log('No data available for today');
                  }
              } catch (error) {
                  console.error('Error:', error);
              }
          }

          getStats();
          EOL

      - name: Run stats script
        run: node stats.js

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add analytics/daily-stats.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update daily stats" && git push)
